
name: "credit_card"

# These parameters govern how a raw CSV file
# from e.g. a bank account will be ingested.
read_csv_opts:
    sep: ","
cols:
    date: "Transaction Date" 
    description: "Description"
    original_category: "Category"
    amount: "Amount"

# Categories are treated mutually exclusively. 
# The order of these entries matters -- an expense
# will be put into the first category it matches. 
categories:
    lunch:
        description: ["CAVA", "CHIPOTLE"]
    groceries:
        original_category: ["Groceries"]
        description: ["STAR MARKET", "COSTCO"]
    coffee:
        description: ["NERO", "TATTE", "COLECTIVO"]
    eating_out:
        original_category: ["Food & Drink"]
    bicycle:
        description: ["BICYC"]
    moving:
        description: ["U-HAUL", "AIRBNB", "CITY OF BOSTON"]
    Target:
        description: ["TARGET"]
    Amazon:
        description: ["AMZN", "Amazon"]
    travel:
        description: ["UBER", "DELTA", "UNITED"]
    clothing:
        description: ["REI", "LEVIS", "Icebreaker"]
    credit_card_payment:
        description: ["PAYMENT", "Payment"]


##############################################################
# This parameter allows us to detect transactions between 
# this account and another held account (i.e., a transfer); 

transactors:
    checking_account:
        original_category: ["PAYMENT", "Payment"]

 
